CREATE DATABASE loggin;
USE loggin;
CREATE TABLE IF NOT EXISTS USUARIO(
ID INT auto_increment primary key,
NOMBRE VARCHAR(15),
CONTRASEÑA VARCHAR(20)
);
# ------  SP ---------------
#--- CREAR
DELIMITER //
CREATE PROCEDURE sp_CrearUsuario(
    IN p_Nombre VARCHAR(15),
    IN p_Contraseña VARCHAR(20)
)
BEGIN
    INSERT INTO USUARIO (NOMBRE, CONTRASEÑA) VALUES (p_Nombre, p_Contraseña);
END //
DELIMITER ;
#----LEER
DELIMITER //
CREATE PROCEDURE sp_ObtenerUsuario(
    IN p_ID INT
)
BEGIN
    SELECT * FROM USUARIO WHERE ID = p_ID;
END //
DELIMITER ;

#----ACTUALIZAR
DELIMITER //
CREATE PROCEDURE sp_ActualizarUsuario(
    IN p_ID INT,
    IN p_Nombre VARCHAR(15),
    IN p_Contraseña VARCHAR(20)
)
BEGIN
    UPDATE USUARIO SET NOMBRE = p_Nombre, CONTRASEÑA = p_Contraseña WHERE ID = p_ID;
END //
DELIMITER ;

#----ELIMINAR
DELIMITER //
CREATE PROCEDURE sp_EliminarUsuario(
    IN p_ID INT
)
BEGIN
    DELETE FROM USUARIO WHERE ID = p_ID;
END //
DELIMITER ;

